### PR TITLE
Pass current file into locals

### PR DESCRIPTION
**Pull request by just-boris**
This feature could be useful when you creating navigation menu in layout. Now I can't get the current filename. This fix adds ability to generate menu like this:

``` jade
ul
    each item in menu
        li(class= item.name == file.path ? 'active' : '')
             a(href=item.href)= item.name
```

### CODE REVIEW

**Comment by michealbenedict** [comment]
Can you add this to the README.md as well?

Secondly, I have merged your previous PR (tests), so could you rebase off master to ensure your PR is updated?

Thanks!

**Comment by just-boris** [comment]
Certainly. Please view the new changes

**Comment by michealbenedict** [comment]
Thanks @just-boris!

**Comment by just-boris** [comment]
Could you make a release with this fix?
I want to switch to stable version in my project.

**Comment by michealbenedict** [comment]
Pushed, 0.0.4

Thanks once again!

**Pull request merged**
